### ISSUE TITLE
README update: python version

### ISSUE THREAD

**Issue by xanubsl** [bedapub/besca#204] opened 2022-04-27 13:02 UTC
Within the README, conda instructions still call for python=3.7.1 while newest besca requires python 3.8.

**Comment by paulgeser** [comment] 2022-07-01 08:24
Will take a look at the issue

**Comment by paulgeser** [comment] 2022-07-01 08:33
After checking I saw that the version was already upgraded to 3.9

**Comment by paulgeser** [comment] 2022-07-01 08:34
Please tell me, if the issue is with that resolved, then I can close the issue

**Comment by hatjek** [comment] 2022-08-18 12:03
Can we close this issue @paulgeser or @yannik-benndorf ?

**Comment by paulgeser** [comment] 2022-08-25 06:32
Implementation has been merged(#235) into master, therefore this issue will be closed.

**Closed by paulgeser** 2022-08-25 06:32 UTC
